version: '3'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/app
    
    # environment:
    #   - MONGO_URI=mongodb://mongodb:27017/lincodeDB
    #   - REDIS_HOST=redis
    #   - REDIS_PORT=6379

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongodb_data: